# Overview

## Functional analysis of -Omics data 
Workshop 2024

### General information

The workshop covers the bioinformatics concepts and tools available for interpreting a gene list using gene ontology and pathway information. The workshop focuses on the principles and concepts required for analyzing and conducting functional and pathway analysis on a gene list from any organism, although the focus will be on human and model eukaryotic organisms.

### Course Objectives

Participants will gain practical experience and skills to be able to:

- Understand basic concepts of functional enrichment analysis;
- Interpret enrichment analysis results;
- Get systems perspective of gene functions;
- Get more information about a gene list;
- Discover what pathways are enriched in a gene list (and use it for hypothesis generation);
- Predict gene function and extend a gene list;
- Follow workflow after the workshop to conduct their own analysis.

### Target Audience

This workshop is intended for biologists working with ‘-Omics data’ (e.g. RNA-Seq, protein expression and other omics data), who are interested in interpreting large gene/protein lists resulting from their experiments.

### Setup Requirements

This workshop will be delivered online over zoom; you may wish to install the dedicated zoom. Otherwise, no special software installation will required, as we will be using online analysis tools.  

 * Zoom Link: 


Links and material will be provided on the day. BYO coffee.


### Schedule

| Day  | Time  | Item | Activity | Time (mins) |
|------|-------|------|----------|-------------|
| **Day 1** | 3 hrs |      | **Welcome and housekeeping** | 10          |
|        |       | HK   | Introduction | 10          |
|        |       | HK   | Data acquisition | 5           |
|        |       | HK   | Filtering gene list | 15          |
|        |       | HK   | Hands-on with Interactive Calculator (breakout rooms) | 15          |
|        |       |      | [Interactive Calculator](https://bioinformatics3.erc.monash.edu/rsconnect/content/241/) |             |
|        |       | HK   | gProfiler [GO + pathways] | 20          |
|        |       |      | [gProfiler](https://biit.cs.ut.ee/gprofiler/gost) |             |
|        |       | HK   | Hands-on with gProfiler (breakout rooms) | 20          |
|        |       | HK   | Break | 15          |
|        |       | HK   | STRING | 20          |
|        |       |      | [STRING](https://string-db.org/) |             |
|        |       | HK   | Reactome | 20          |
|        |       |      | [Reactome](https://reactome.org/) |             |
|        |       | HK   | GSEA (GenePattern) | 30          |
|        |       |      | [GSEA (GenePattern)](https://cloud.genepattern.org/gp/pages/index.jsf) |             |
| **Day 2** | 3 hrs |      | **Welcome and housekeeping** | 5           |
|        |       | HK   | Day-1 recap | 15          |
|        |       | CW   | Using R for functional enrichment analysis | 30          |
|        |       |      | **Applications and advantages** |             |
|        |       |      | Working with confidential data |             |
|        |       |      | Customisation, flexibility, reproducibility |             |
|        |       |      | Automation and batch processing |             |
|        |       | CW   | Available packages in R | 5           |
|        |       |      | Clusterprofiler |             |
|        |       |      | Gprofiler |             |
|        |       |      | Any other? |             |
|        |       | CW   | Introducing R, R Markdown, Rstudio | 30          |
|        |       |      | Getting logged on RStudio environment |             |
|        |       |      | Discuss R Markdown |             |
|        |       |      | Discuss basic features of Rstudio |             |
|        |       | CW   | Clusterprofiler - Hands-on | 30          |
|        |       |      | Breakout rooms |             |
|        |       | CW   | Work on and discuss results based on following criterion | 30          |
|        |       |      | **Analysis** |             |
|        |       |      | ORA |             |
|        |       |      | GSEA |             |
|        |       |      | Ontologies (GO) |             |
|        |       |      | Pathway (KEGG, Reactome) |             |
|        |       |      | Visualisations |             |
|        |       | CW   | gprofiler - Hands-on | 30          |
|        |       |      | Breakout rooms |             |
|        |       | CW   | Work on and discuss specific features | 30          |
|        |       |      | gost function with standard analysis and plots - Discuss how the plots from gprofiler are different (than clusterprofiler) and also useful |             |
|        |       |      | Send analysis from R to g:Profiler web interface |             |
|        |       |      | Sharing the results easily with colleagues |             |
|        |       |      | To accompany a publication without the peers having to run the full analysis code in R |             |
|        |       |      | Integrating results with external tools for visualisations |             |
|        |       |      | Alter results using ggplot2, enrichplot, clusterProfiler |             |
|        |       |      | Using custom annotations |             |
|        |       |      | Non-model organisms, that are not annotated in the Ensembl database |             |
|        |       |      | Enable users to upload custom annotation files |             |
|        |       | CW   | Experiment wrap up | 30          |
|        |       |      | Discuss results |             |
|        |       |      | Enrichments look different from different tools - Why |             |
|        |       |      | Wrap up and feedback | 5           |

<!-- ### Abbreviations -->

- **HK**: Hossein V Kahrood
- **CW**: Cali Willet

### Post-workshop survey

We appreciate your feedback (both positive and negative !) - please fill out the short post-workshop survey [Feedback Survey](https://docs.google.com/forms/d/e/1FAIpQLSdmWreDIWjVsIR5g22jvcypH8ChFyMJ506HTAIoMIJYzjD-3Q/viewform) in the last 5 mins.