# GSEA with clusterProfiler


[clusterProfiler](https://bioconductor.org/packages/release/bioc/html/clusterProfiler.html) is a comprehensive suite of enrichment tools. It has functions to run ORA or GSEA over commonly used databases (GO, KEGG, KEGG Modules, DAVID, Pathway Commons, WikiPathways) as well as generic functions to perform ORA or GSEA with custom gene sets.

It has a companion plotting package [enrichplot](https://www.bioconductor.org/packages/release/bioc/html/enrichplot.html) dedicated to plotting enrichment results. 

The `clusterProfiler` user guide can be found [here](https://bioconductor.org/packages/devel/bioc/manuals/clusterProfiler/man/clusterProfiler.pdf). 

The `enrichplot` user guide can be found [here](https://www.bioconductor.org/packages/devel/bioc/manuals/enrichplot/man/enrichplot.pdf). 

One of the challenges when working with `clusterProfiler` for FEA is that each enrichment function has different supported organisms and different namespace requirements, so you can not necessarily use all of the functions over the same gene list. In this activity, we will review the FEA functions and investigate their requirements, before performing a gene ID conversion with the `bitr` function to enable compatability with our [Pezzini et al 2017](https://link.springer.com/article/10.1007/s10571-016-0403-y) dataset. 

<p>&nbsp;</p>  <!-- insert blank line -->

## Activity overview

1. Explore the functions of `clusterProfiler` including which FEA functions support which organisms and which namespaces
2. Load input dataset (a gene matrix with adjusted P values and log2 fold change values) 
3. Extract the gene IDs and sort by log2 fold change to create the GSEA gene list R object
4. Use `bitr` to convert gene IDs from ENSEMBL to ENTREZ for compatability with `gseKEGG`
5. Perform GSEA with `gseKEGG`
6. Visualise results with `enrichplot`

<p>&nbsp;</p>  <!-- insert blank line -->

&#x27A4; Go back to your RStudio interface and clear your environment by selecting `Session` &rarr; `Quit session` &rarr; `Dont save` &rarr;`Start new session`


<p>&nbsp;</p>  <!-- insert blank line -->

&#x27A4; Open the `clusterProfiler.Rmd` notebook using `File` &rarr; `Open file`, or use the keyboard shortcut `ctrl + o`. 


**Instructions for the analysis will continue from the notebook.**

<p>&nbsp;</p>  <!-- insert blank line -->

## End of activity summary

- We have explored the supported organisms and namespaces of the `clusterProfiler`enrichment functions 
- We have extracted a ranked gene list for GSEA and converted the gene IDs for compatability with `gseKEGG`
- We have performed GSEA on the KEGG database with `gseKEGG` and visualised the results with multiple plot types 
- We have captured all version details relevant to the session within the R notebook

<p>&nbsp;</p>  <!-- insert blank line -->

## Poll

❓What was your favourite R plot from this activity? 🤔

This may be the one you found most informative, easiest to interpret, most eye-catching... 

