# WebGestaltR

`WebGestaltR` is the R version of the web application [WebGestalt](www.webgestalt.org), "WEB-based GEne SeT AnaLysis Toolkit". 

This tool (both the web and R versions) has many features and advantages: 

- Simple to run 
- Runs ORA, GSEA, and NTA (network topology analysis)
- Natively supports 12 organisms
- Can be used for novel species (we will do this in the final session)
- Supports many namespaces (n = 73 for human) 
- Does not require namespace conversion between the databases like  `clusterProfiler` does, and even allows different namespaces between query gene list and ORA background gene list 
- Supports many databases/gene sets (n = 70 for human) including 'nonredundant' versions of GO
- Supports metabolomics, with 15 different ID types, described in [Elizarraras et al 2024](https://academic.oup.com/nar/article/52/W1/W415/7684598)
- Can run query against multiple databases simultaneously by providing database names as a list to the enrichment function
- Saves all results files to disk when running, no need to save  individual files manually
- Creates interactive HTML reports with various plots and filter options and with term links to external databases
- Supports multi-threading, parallelisation, and batch processing of multiple queries 
 




## Activity overview

1. Explore the organisms, databases/gene sets and namespaces supported natively
2. Run GSEA over KEGG database and explore the HTML output
3. Run ORA over multiple databases simultaneously 
4. Explore the impact of using the 'non-redundant' GO database to the full GO database 


** add the use of enrichplot with these results!


<p>&nbsp;</p>  <!-- insert blank line -->



&#x27A4; Go back to your RStudio interface and clear your environment by selecting `Session` &rarr; `Quit session` &rarr; `Dont save` &rarr; `Start new session`



&#x27A4; Open the `WebGestaltR.Rmd` notebook by clicking on it in the `Files` pane

You could also open the file by selecting `File` &rarr; `Open file`, or use the keyboard shortcut `ctrl + o`. 


**<span style="color: #006400;">Instructions for the analysis will continue from the R notebook.</span>**


<p>&nbsp;</p>  <!-- insert blank line -->

## End of activity summary